vich_uploader:
    db_driver: orm
    
    #metadata pour la possibilité d'utiliser des annotations de type "attributs"
    metadata:
        type: attribute
        
    #Configuration du mapping
    mappings:
        visites:
            uri_prefix: /images/visites
            upload_destination: '%kernel.project_dir%/public/images/visites'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
   